### ISSUE TITLE
__version__.txt is missing 

### ISSUE THREAD

**Issue by diefenbach** [jochym/Elastic#3]
During installation via pip this error happens:

   Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-DPwm2Z/elastic/setup.py", line 5, in <module>
        with open("__version__.txt") as w:
    IOError: [Errno 2] No such file or directory: '__version__.txt'

Seems that __version__.txt is missing within the release package version 4.0.28.

**Comment by jochym** [comment]
Thanks!
I will deal with it during weekend.
P.

śr., 8 cze 2016, 09:41 użytkownik Kai Diefenbach <notifications@github.com>
napisał:

**Comment by jochym** [comment]
I have switched to different versioning scheme. This should work now.
