### ISSUE TITLE
Wrong coefficients in `hexagonal`

### ISSUE THREAD

**Issue by yuzie007** [jochym/Elastic#65]
Apart from #64, I would also like to report wrong coefficients in `hexagonal`.

[Here](https://github.com/jochym/Elastic/blob/6117c9aeff8859a46860a34057e2f59c71c5a841/elastic/elastic.py#L221), we have unnecessary coefficients of 2. This is inconsistent with the [Elastic document itself](https://elastic.readthedocs.io/en/stable/intro.html) as well as my own derivation ([main.pdf](https://github.com/jochym/Elastic/files/14935776/main.pdf)).

To demonstrate this is really an issue, I have conducted a test calculation for graphite ([graphite_gaussian.zip](https://github.com/jochym/Elastic/files/14935656/graphite_gaussian.zip)). In experiments (Ref. 11 in [this](https://doi.org/10.1002/pssb.200879604)):

- C11 = 1060 GPa, C12 = 180 GPa, C13 = 15 GPa, C33 = 36.5 GPa, C44 = 4 GPa, C66 = (C11-C12)/2 = 440 GPa

Fo DFT (PBE-D3(BJ)), using VASP IBRION=6, I obtain (without ionic-relaxation contribution)

- C11 = 1075 GPa, C12 = 237 GPa, C13 = -4 GPa, C33 = 36 GPa, C44 = -5 GPa, C66 = (C11-C12)/2 = 419 GPa

Using Elastic with `get_elastic_tensor` (which calls `hexagonal`) I get

- C11 = 948 GPa, C12 = 69 GPa  C13 = -3 GPa, C33 = 36 GPa, C44 = -5 GPa, C66 = (C11-C12)/2 = 440 GPa 

Which is substantially deviated from the IBRION=6 values for C11 and C12, because of the coefficient error in `hexagonal`.

If we use the one-axis approach (i.e., without `hexagonal`) (with solving the issue in #64), I get

- C11 = 1090 GPa, C12 = 225 GPa, C13 = -4 GPa, C33 = 36 GPa, C44 = -6 GPa, C66 = (C11-C12)/2 = 432 GPa

Which is consistent with IBRION=6.

If we will fix the coefficients in `hexagonal`, then `get_elastic_tensor` gives

- C11 = 1077 GPa, C12 = 240 GPa C13 = -3 GPa, C33 = 36 GPa, C44 = -5 GPa, C66 = (C11-C12)/2 = 419 GPa

which is consistent with IBRION=6.

**Comment by jochym** [comment]
Thanks again @yuzie007 ! I will review the change and get back to you.

**Comment by jochym** [comment]
@yuzie007: It seems you are right. Thanks. I will merge your change as a first one after update of the build tool chain - which I am doing right now.
